[database]
url = "db.sqlite"

[service]
produce_digest_interval_seconds = 10800
message_log_directory = "messages"
port = 3000
host = "127.0.0.1"
max_gpt_request_tokens = 2048

[discord]
channel_ids = []